# Generated by Django 5.2.16 on 2026-08-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0025_paciente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenestudio',
            name='archivo_original',
            field=models.FileField(blank=True, null=True, upload_to='imagenes_estudio/dicom_original/%Y/%m/'),
        ),
    ]
