# Generated by Django 5.2.16 on 2026-08-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0026_imagenestudio_archivo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenestudio',
            name='seleccionada',
            field=models.BooleanField(default=True),
        ),
    ]
