# Generated by Django 5.2.16 on 2026-08-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0027_imagenestudio_seleccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='resultados_enviados_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
