# Generated by Django 5.2.16 on 2026-08-27 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0028_ordentrabajo_resultados_enviados_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoestudio',
            name='precio',
        ),
        migrations.AddField(
            model_name='tipoestudio',
            name='modalidad',
            field=models.CharField(choices=[('rx', 'Rayos X'), ('rx_contraste', 'Rayos X con contraste / fluoroscopía'), ('tac', 'Tomografía (TAC)'), ('usg', 'Ultrasonido / Doppler'), ('mamo_densit', 'Mamografía / Densitometría')], default='rx', help_text='Agrupa el estudio por equipo/sala y define qué técnico y radiólogo pueden atenderlo.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tipoestudio',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='PrecioEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(choices=[('coex', 'COEX'), ('privado', 'Privado'), ('emergencia_igss', 'Emergencia IGSS')], max_length=20)),
                ('horario_habil', models.BooleanField(choices=[(True, 'Hábil'), (False, 'Inhábil (después de las 18:00 en privado y emergencia)')], default=True, verbose_name='horario')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='pacientes.tipoestudio')),
            ],
            options={
                'verbose_name': 'precio de estudio',
                'verbose_name_plural': 'precios de estudio',
                'db_table': 'precios_estudio',
                'ordering': ['tipo_estudio', 'convenio', '-horario_habil'],
                'unique_together': {('tipo_estudio', 'convenio', 'horario_habil')},
            },
        ),
    ]
