# Generated by Django 5.2.16 on 2026-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0030_cargar_catalogo_normalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('agendada', 'Agendada'), ('en_espera', 'En espera'), ('en_proceso', 'En proceso'), ('procesada', 'Procesada'), ('ausente', 'Ausente'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
