# Generated by Django 5.2.16 on 2026-08-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0031_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='token_publico',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
