# Generated by Django 5.2.16 on 2026-08-28 23:55

from django.db import migrations, models


def backfill_orden(apps, schema_editor):
    """Tickets creados antes de este campo: usa su número de turno como
    posición inicial en la fila (equivalente a no haber sido adelantados)."""
    Ticket = apps.get_model('pacientes', 'Ticket')
    for ticket in Ticket.objects.filter(orden=0, numero__gt=0):
        ticket.orden = ticket.numero
        ticket.save(update_fields=['orden'])


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0031_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-prioridad', 'orden'], 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='orden',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Posición dentro de la fila de espera del día. Normalmente coincide con el número de turno, pero puede adelantarse (ver `adelantar`) sin que eso cambie el número oficial del turno.'),
        ),
        migrations.RunPython(backfill_orden, migrations.RunPython.noop),
    ]
