# Generated by Django 5.2.16 on 2026-09-02 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0033_alter_ticket_options_ticket_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de cobro'), ('pagado', 'Cobrado')], default='pendiente', max_length=20)),
                ('pagado_en', models.DateTimeField(blank=True, null=True, verbose_name='pagado el')),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cobro', to='pacientes.cita')),
                ('cobrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cobro',
                'verbose_name_plural': 'cobros',
                'db_table': 'cobros',
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('aplica_descuento', models.BooleanField(default=False, help_text='Si se activa, el total se calcula restando el porcentaje de descuento.', verbose_name='aplicar descuento')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, help_text='Solo se usa si "aplicar descuento" está marcado.', max_digits=5, verbose_name='% de descuento')),
                ('estudios', models.ManyToManyField(blank=True, related_name='combos', to='pacientes.tipoestudio', verbose_name='estudios del combo')),
            ],
            options={
                'verbose_name': 'combo',
                'verbose_name_plural': 'combos',
                'db_table': 'combos',
                'ordering': ['nombre'],
            },
        ),
    ]
