# Generated by Django 5.2.16 on 2026-09-05 17:02

from django.db import migrations, models


def asignar_expedientes(apps, schema_editor):
    """Numera los pacientes ya existentes por orden de registro (id)."""
    Paciente = apps.get_model('pacientes', 'Paciente')
    for numero, paciente in enumerate(Paciente.objects.order_by('id'), start=1):
        paciente.expediente = f'{numero:06d}'
        paciente.save(update_fields=['expediente'])


def borrar_expedientes(apps, schema_editor):
    Paciente = apps.get_model('pacientes', 'Paciente')
    Paciente.objects.update(expediente=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0034_cobro_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='expediente',
            field=models.CharField(
                blank=True, editable=False, max_length=12, null=True, unique=True,
                verbose_name='N° de expediente',
                help_text='Número de expediente que el sistema asigna al registrar al paciente.',
            ),
        ),
        migrations.RunPython(asignar_expedientes, borrar_expedientes),
    ]
