# Generated by Django 5.2.16 on 2026-09-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0034_cobro_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Pendiente'), ('enviado', 'Enviado')], default='borrador', max_length=20),
        ),
    ]
