# Generated by Django 5.2.16 on 2026-09-03 13:55

from django.db import migrations


class Migration(migrations.Migration):
    """Sin operaciones: en esta rama `forma_pago` y `numero_boleta` ya los crea
    0034_cobro_combo, así que agregarlos otra vez fallaba con "Duplicate column
    name" al migrar una base de datos desde cero. Se conserva el archivo (vacío)
    para que las bases que ya lo tenían aplicado sigan siendo consistentes."""

    dependencies = [
        ('pacientes', '0035_alter_reportediario_estado'),
    ]

    operations = []
