# Generated by Django 5.2.16 on 2026-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0035_alter_reportediario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AddField(
            model_name='cobro',
            name='numero_boleta',
            field=models.CharField(blank=True, max_length=60, verbose_name='número de boleta / referencia'),
        ),
    ]
