# Generated by Django 5.2.16 on 2026-09-12 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0035_paciente_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cita_asignada', 'Nueva cita asignada'), ('cita_confirmada', 'Cita confirmada'), ('cita_rechazada', 'Cita rechazada'), ('orden_pendiente', 'Nueva orden de trabajo pendiente'), ('estudio_listo_informar', 'Estudio listo para informar'), ('estudio_completado', 'Estudio completado'), ('datos_paciente_pendientes', 'Datos de paciente pendientes de llenar'), ('reporte_enviado', 'Reporte diario enviado'), ('estudio_extra_agregado', 'Estudio extra agregado')], max_length=30),
        ),
        migrations.CreateModel(
            name='EstudioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_extra_agregados', to=settings.AUTH_USER_MODEL)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_extra', to='pacientes.cita')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.tipoestudio')),
            ],
            options={
                'verbose_name': 'estudio extra',
                'verbose_name_plural': 'estudios extra',
                'db_table': 'estudios_extra',
                'ordering': ['creado_en'],
            },
        ),
    ]
