# Generated by Django 5.2.16 on 2026-09-12 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0035_paciente_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='comprobante_bancario',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_bancarios/%Y/%m/', verbose_name='boleta o comprobante bancario'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='constancia_firmada',
            field=models.FileField(blank=True, null=True, upload_to='constancias_pago_firmadas/%Y/%m/', verbose_name='constancia firmada'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='constancia_subida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobro',
            name='constancia_subida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constancias_pago_subidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
