# Generated by Django 5.2.16 on 2026-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0036_cobro_forma_pago_cobro_numero_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de confirmar'), ('agendada', 'Confirmada'), ('en_espera', 'En espera'), ('en_proceso', 'En proceso'), ('procesada', 'Procesada'), ('ausente', 'Ausente'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
