# Generated by Django 5.2.16 on 2026-09-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0036_cobro_comprobante_bancario_cobro_constancia_firmada_and_more'),
        ('pacientes', '0037_alter_cita_estado'),
    ]

    operations = [
    ]
