# Generated by Django 5.2.16 on 2026-09-13 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0038_alter_paciente_sexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecioEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(choices=[('coex', 'COEX'), ('privado', 'Privado'), ('emergencia_igss', 'Emergencia IGSS')], max_length=20)),
                ('horario_habil', models.BooleanField(choices=[(True, 'Hábil'), (False, 'Inhábil (después de las 18:00 en privado y emergencia)')], default=True)),
                ('valor_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_precio_estudio_realizados', to=settings.AUTH_USER_MODEL)),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='pacientes.tipoestudio')),
            ],
            options={
                'verbose_name': 'cambio de precio de estudio',
                'verbose_name_plural': 'historial de precios de estudio',
                'db_table': 'historial_precios_estudio',
                'ordering': ['-creado_en'],
            },
        ),
    ]
