# Generated by Django 5.2.16 on 2026-09-19 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0039_historialprecioestudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modalidad',
                'verbose_name_plural': 'modalidades',
                'db_table': 'modalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_anterior', models.CharField(blank=True, max_length=120)),
                ('accion', models.CharField(choices=[('crear', 'Creada'), ('editar', 'Editada'), ('eliminar', 'Eliminada')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_modalidades_realizados', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='pacientes.modalidad')),
            ],
            options={
                'verbose_name': 'historial de modalidad',
                'verbose_name_plural': 'historial de modalidades',
                'db_table': 'historial_modalidades',
                'ordering': ['-creado_en'],
            },
        ),
    ]
