# Generated by Django 5.2.16 on 2026-09-18 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0039_historialprecioestudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(choices=[('coex', 'COEX'), ('privado', 'Privado'), ('emergencia_igss', 'Emergencia IGSS')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de boleta'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_boleta', models.CharField(blank=True, max_length=60)),
                ('comprobante_bancario', models.FileField(blank=True, null=True, upload_to='comprobantes_ordenes_pago/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='pacientes.combo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='pacientes.paciente')),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago_confirmadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes_pago',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_pago', to='pacientes.cita')),
                ('estudio_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pago', to='pacientes.estudioextra')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.tipoestudio')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pacientes.ordenpago')),
            ],
            options={
                'db_table': 'detalles_orden_pago',
            },
        ),
    ]
