# Generated by Django 5.2.16 on 2026-09-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0040_modalidad_historialmodalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidad',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='código'),
        ),
    ]
