# Generated by Django 5.2.16 on 2026-09-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0040_ordenpago_detalleordenpago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modalidad',
                'verbose_name_plural': 'modalidades',
                'db_table': 'modalidades',
                'ordering': ['nombre'],
            },
        ),
        # Nota: los campos correccion_*/validacion_* de OrdenTrabajo y el
        # AlterField de notificacion.tipo NO van acá -- ya los agregó, con
        # el mismo estado final, la migración 0043_validacion_tecnico_estudio
        # (construida en paralelo en la rama Marilin). Se quitaron de acá al
        # fusionar Elmer con Marilin para no intentar crear las mismas
        # columnas dos veces.
        migrations.AlterField(
            model_name='tipoestudio',
            name='modalidad',
            field=models.CharField(default='rx', help_text='Agrupa el estudio por equipo/sala y define qué técnico y radiólogo pueden atenderlo.', max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_anterior', models.CharField(blank=True, max_length=120)),
                ('accion', models.CharField(choices=[('crear', 'Creada'), ('editar', 'Editada'), ('eliminar', 'Desactivada')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_modalidades_realizados', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='pacientes.modalidad')),
            ],
            options={
                'verbose_name': 'historial de modalidad',
                'verbose_name_plural': 'historial de modalidades',
                'db_table': 'historial_modalidades',
                'ordering': ['-creado_en'],
            },
        ),
    ]
