# Generated by Django 5.2.16 on 2026-09-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0040_ordenpago_detalleordenpago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modalidad',
                'verbose_name_plural': 'modalidades',
                'db_table': 'modalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='correccion_detalle',
            field=models.CharField(blank=True, max_length=255, verbose_name='qué cambió recepción'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='correccion_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='correccion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_corregidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='validacion_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='validacion_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de verificación del técnico'), ('correcto', 'Estudio correcto'), ('modificacion', 'Modificación solicitada a recepción'), ('corregido', 'Actualizado por recepción, falta confirmar')], default='correcto', max_length=15, verbose_name='verificación del técnico'),
            # Las órdenes que ya existían se consideran verificadas, para no
            # bloquear en Caja lo que se generó antes de esta función.
            preserve_default=False,
        ),
        # Las órdenes nuevas sí arrancan pendientes de verificación.
        migrations.AlterField(
            model_name='ordentrabajo',
            name='validacion_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de verificación del técnico'), ('correcto', 'Estudio correcto'), ('modificacion', 'Modificación solicitada a recepción'), ('corregido', 'Actualizado por recepción, falta confirmar')], default='pendiente', max_length=15, verbose_name='verificación del técnico'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='validacion_nota',
            field=models.TextField(blank=True, help_text='Lo que el técnico le pidió cambiar a recepción.', verbose_name='qué hay que modificar'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='validacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cita_asignada', 'Nueva cita asignada'), ('cita_confirmada', 'Cita confirmada'), ('cita_rechazada', 'Cita rechazada'), ('orden_pendiente', 'Nueva orden de trabajo pendiente'), ('estudio_listo_informar', 'Estudio listo para informar'), ('estudio_completado', 'Estudio completado'), ('datos_paciente_pendientes', 'Datos de paciente pendientes de llenar'), ('reporte_enviado', 'Reporte diario enviado'), ('estudio_extra_agregado', 'Estudio extra agregado'), ('estudio_validado', 'Estudio verificado, listo para cobrar'), ('modificacion_solicitada', 'Modificación de estudio solicitada'), ('estudio_actualizado', 'Estudio actualizado por recepción'), ('cita_cancelada', 'Cita cancelada por recepción')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tipoestudio',
            name='modalidad',
            field=models.CharField(default='rx', help_text='Agrupa el estudio por equipo/sala y define qué técnico y radiólogo pueden atenderlo.', max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_anterior', models.CharField(blank=True, max_length=120)),
                ('accion', models.CharField(choices=[('crear', 'Creada'), ('editar', 'Editada'), ('eliminar', 'Desactivada')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_modalidades_realizados', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='pacientes.modalidad')),
            ],
            options={
                'verbose_name': 'historial de modalidad',
                'verbose_name_plural': 'historial de modalidades',
                'db_table': 'historial_modalidades',
                'ordering': ['-creado_en'],
            },
        ),
    ]
