# Generated by Django 5.2.16 on 2026-09-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0040_ordenpago_detalleordenpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpago',
            name='notas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
