# Generated by Django 5.2.16 on 2026-09-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0041_modalidad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoestudio',
            name='modalidad',
            field=models.CharField(default='rx', help_text='Agrupa el estudio por equipo/sala y define qué técnico y radiólogo pueden atenderlo.', max_length=30),
        ),
    ]
