# Generated by Django 5.2.16 on 2026-09-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0042_seed_modalidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='tipo_estudio_generado',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_origen', to='pacientes.tipoestudio'),
        ),
    ]
