# Generated by Django 5.2.16 on 2026-09-19 21:48, reordenada a mano para
# poder migrar los datos existentes antes de borrar los campos viejos.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_informes_e_imagenes(apps, schema_editor):
    """Antes de este cambio, toda cita era de un solo estudio (el feature de
    combos recién se agregó): así que para cada OrdenTrabajo con informe
    guardado, el "tipo_estudio" del informe es el mismo de la cita, y todas
    sus imágenes ya viejas son de ese mismo estudio."""
    OrdenTrabajo = apps.get_model('pacientes', 'OrdenTrabajo')
    InformeEstudio = apps.get_model('pacientes', 'InformeEstudio')
    ImagenEstudio = apps.get_model('pacientes', 'ImagenEstudio')

    for orden in OrdenTrabajo.objects.select_related('cita').all():
        tipo_estudio_id = orden.cita.tipo_estudio_id
        if orden.informe_texto or orden.informe_archivo:
            InformeEstudio.objects.create(
                orden=orden,
                tipo_estudio_id=tipo_estudio_id,
                texto=orden.informe_texto,
                archivo=orden.informe_archivo.name,
                creado_por_id=orden.informe_creado_por_id,
                creado_en=orden.informe_creado_en,
            )
        ImagenEstudio.objects.filter(orden=orden, tipo_estudio__isnull=True).update(
            tipo_estudio_id=tipo_estudio_id,
        )


def deshacer_migracion_informes(apps, schema_editor):
    """No hay forma de volver un InformeEstudio a los campos viejos de
    OrdenTrabajo sin perder informes de combos (que no cabrían en un solo
    campo) -- este paso queda como no-op a propósito."""


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0043_combo_tipo_estudio_generado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenestudio',
            name='tipo_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.tipoestudio'),
        ),
        migrations.CreateModel(
            name='InformeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, verbose_name='informe (texto)')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='informes/%Y/%m/', verbose_name='informe (archivo)')),
                ('creado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes_creados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='pacientes.ordentrabajo')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.tipoestudio')),
            ],
            options={
                'verbose_name': 'informe de estudio',
                'verbose_name_plural': 'informes de estudio',
                'db_table': 'informes_estudio',
                'ordering': ['tipo_estudio__nombre'],
                'unique_together': {('orden', 'tipo_estudio')},
            },
        ),
        migrations.RunPython(migrar_informes_e_imagenes, deshacer_migracion_informes),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='informe_archivo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='informe_creado_en',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='informe_creado_por',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='informe_texto',
        ),
    ]
