# Generated by Django 5.2.16 on 2026-09-25 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0043_validacion_tecnico_estudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstudioProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('modalidad', models.CharField(max_length=30)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('precio_coex_habil', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_privado_habil', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_privado_inhabil', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_emergencia_igss_habil', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_emergencia_igss_inhabil', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_vigencia', models.DateField(verbose_name='vigente desde')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estudio_programados_cancelados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estudio_programados_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_programados', to='pacientes.tipoestudio')),
            ],
            options={
                'verbose_name': 'cambio de estudio programado',
                'verbose_name_plural': 'cambios de estudio programados',
                'db_table': 'cambios_estudio_programados',
                'ordering': ['fecha_vigencia', 'creado_en'],
            },
        ),
    ]
