# Generated by Django 5.2.16 on 2026-09-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0044_remove_ordentrabajo_informe_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpago',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='pacientes.paciente'),
        ),
    ]
