# Generated by Django 5.2.16 on 2026-09-22 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0045_alter_ordenpago_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoTratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'médico tratante',
                'verbose_name_plural': 'médicos tratantes',
                'db_table': 'medicos_tratantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='codigo_igss',
            field=models.CharField(blank=True, help_text='Código de orden/autorización que emite IGSS para este estudio (COEX / Emergencia IGSS).', max_length=50, verbose_name='código IGSS'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico_tratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.medicotratante', verbose_name='médico tratante'),
        ),
    ]
