# Generated by Django 5.2.16 on 2026-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0046_medicotratante_cita_codigo_igss_cita_medico_tratante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioextra',
            name='procesar_ahora',
            field=models.BooleanField(default=False, help_text='El técnico puede subir las imágenes de este estudio ya mismo, sin esperar a que se suba su informe (igual que un combo).', verbose_name='procesar ahora'),
        ),
    ]
