# Generated by Django 5.2.16 on 2026-09-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0044_cambio_estudio_programado'),
        ('pacientes', '0047_estudioextra_procesar_ahora'),
    ]

    operations = [
    ]
