# Generated by Django 5.2.16 on 2026-10-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0048_merge_20260924_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicotratante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='medicotratante',
            name='dpi',
            field=models.CharField(blank=True, help_text='Llave de acceso al visor del estudio cuando el tipo es privado o ambos.', max_length=20, null=True, unique=True, verbose_name='DPI'),
        ),
        migrations.AddField(
            model_name='medicotratante',
            name='tipo',
            field=models.CharField(blank=True, choices=[('', 'Sin clasificar'), ('igss', 'IGSS'), ('privado', 'Privado'), ('ambos', 'Ambos')], default='', help_text='De qué lado refiere pacientes: IGSS, privado o ambos.', max_length=10, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='enviado_medico_tratante_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
