# Generated by Django 5.2.16 on 2026-10-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0049_medicotratante_correo_medicotratante_dpi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComisionMedicoTratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField()),
                ('hasta', models.DateField(help_text='Último día del período, incluido.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.FileField(upload_to='comprobantes_comision_medico_tratante/%Y/%m/', verbose_name='comprobante (boleta o transferencia)')),
                ('numero_boleta', models.CharField(blank=True, max_length=60, verbose_name='número de boleta / referencia')),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('medico_tratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_comision', to='pacientes.medicotratante')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_comision_medico_tratante_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago de comisión a médico tratante',
                'verbose_name_plural': 'pagos de comisión a médicos tratantes',
                'db_table': 'pagos_comision_medico_tratante',
                'ordering': ['-hasta', '-desde'],
            },
        ),
        migrations.CreateModel(
            name='PagoComisionMedicoTratanteLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago_comision_medico_tratante', to='pacientes.cita')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pacientes.pagocomisionmedicotratante')),
            ],
            options={
                'db_table': 'pagos_comision_medico_tratante_lineas',
            },
        ),
    ]
