# Generated by Django 5.2.16 on 2026-08-28 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('login_exitoso', 'Inicio de sesión'), ('login_fallido', 'Intento de inicio de sesión fallido'), ('crear_usuario', 'Creación de usuario'), ('editar_usuario', 'Edición de usuario'), ('cambiar_estado_usuario', 'Cambio de estado de usuario (suspensión/reactivación)'), ('editar_comision', 'Cambio de comisión de un usuario'), ('crear_estudio', 'Creación de estudio'), ('editar_estudio', 'Edición de estudio'), ('solicitar_cita', 'Solicitud de cita'), ('confirmar_cita', 'Confirmación de cita'), ('rechazar_cita', 'Rechazo de solicitud de cita'), ('reagendar_cita', 'Reagenda de cita'), ('marcar_llegada', 'Llegada de paciente'), ('marcar_ausente', 'Ausencia de paciente'), ('generar_orden', 'Generación de orden de trabajo'), ('adjuntar_imagenes', 'Carga de imágenes de estudio'), ('seleccionar_imagenes', 'Selección de imágenes del estudio'), ('adjuntar_informe', 'Carga de informe'), ('enviar_estudio', 'Envío de estudio al paciente'), ('registrar_ticket', 'Registro de ticket de emergencia'), ('procesar_ticket', 'Procesamiento de ticket (genera orden de trabajo)'), ('enviar_reporte_diario', 'Envío de reporte diario')], max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('porcentaje_coex', 'porcentaje_coex'), ('porcentaje_privado', 'porcentaje_privado'), ('porcentaje_emergencia_igss', 'porcentaje_emergencia_igss')], max_length=30)),
                ('valor_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_comision_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_comisiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de comisión',
                'verbose_name_plural': 'historial de comisiones',
                'db_table': 'historial_comisiones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
