# Generated by Django 5.2.16 on 2026-08-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salario base mensual'),
        ),
    ]
