# Generated by Django 5.2.16 on 2026-08-29 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usuario_salario_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('login_exitoso', 'Inicio de sesión'), ('login_fallido', 'Intento de inicio de sesión fallido'), ('crear_usuario', 'Creación de usuario'), ('editar_usuario', 'Edición de usuario'), ('cambiar_estado_usuario', 'Cambio de estado de usuario (suspensión/reactivación)'), ('editar_comision', 'Cambio de comisión de un usuario'), ('crear_estudio', 'Creación de estudio'), ('editar_estudio', 'Edición de estudio'), ('solicitar_cita', 'Solicitud de cita'), ('confirmar_cita', 'Confirmación de cita'), ('rechazar_cita', 'Rechazo de solicitud de cita'), ('reagendar_cita', 'Reagenda de cita'), ('marcar_llegada', 'Llegada de paciente'), ('marcar_ausente', 'Ausencia de paciente'), ('generar_orden', 'Generación de orden de trabajo'), ('adjuntar_imagenes', 'Carga de imágenes de estudio'), ('seleccionar_imagenes', 'Selección de imágenes del estudio'), ('adjuntar_informe', 'Carga de informe'), ('enviar_estudio', 'Envío de estudio al paciente'), ('registrar_ticket', 'Registro de ticket / turno'), ('procesar_ticket', 'Procesamiento de ticket (genera orden de trabajo)'), ('adelantar_ticket', 'Adelantó un turno en la fila de espera'), ('avanzar_turno', 'Avanzó la pantalla de turnos (siguiente)'), ('enviar_reporte_diario', 'Envío de reporte diario'), ('registrar_pago_planilla', 'Registro de pago de planilla')], max_length=30),
        ),
        migrations.CreateModel(
            name='PagoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comprobante', models.FileField(upload_to='comprobantes_planilla/%Y/%m/', verbose_name='comprobante (boleta o transferencia)')),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_planilla_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_planilla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago de planilla',
                'verbose_name_plural': 'pagos de planilla',
                'db_table': 'pagos_planilla',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('usuario', 'anio', 'mes')},
            },
        ),
    ]
