# Generated by Django 5.2.16 on 2026-08-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_bitacora_accion_pagoplanilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoplanilla',
            name='numero_boleta',
            field=models.CharField(blank=True, max_length=60, verbose_name='número de boleta / referencia'),
        ),
        migrations.AddField(
            model_name='pagoplanilla',
            name='verificacion_nota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagoplanilla',
            name='verificado',
            field=models.BooleanField(default=False, help_text='El OCR del comprobante confirmó el monto (y el número de boleta, si se indicó).'),
        ),
    ]
