# Generated by Django 5.2.16 on 2026-09-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_pagoplanilla_numero_boleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('login_exitoso', 'Inicio de sesión'), ('login_fallido', 'Intento de inicio de sesión fallido'), ('crear_usuario', 'Creación de usuario'), ('editar_usuario', 'Edición de usuario'), ('cambiar_estado_usuario', 'Cambio de estado de usuario (suspensión/reactivación)'), ('editar_comision', 'Cambio de comisión de un usuario'), ('crear_estudio', 'Creación de estudio'), ('editar_estudio', 'Edición de estudio'), ('solicitar_cita', 'Solicitud de cita'), ('confirmar_cita', 'Confirmación de cita'), ('rechazar_cita', 'Rechazo de solicitud de cita'), ('reagendar_cita', 'Reagenda de cita'), ('marcar_llegada', 'Llegada de paciente'), ('marcar_ausente', 'Ausencia de paciente'), ('generar_orden', 'Generación de orden de trabajo'), ('adjuntar_imagenes', 'Carga de imágenes de estudio'), ('seleccionar_imagenes', 'Selección de imágenes del estudio'), ('adjuntar_informe', 'Carga de informe'), ('enviar_estudio', 'Envío de estudio al paciente'), ('registrar_ticket', 'Registro de ticket / turno'), ('procesar_ticket', 'Procesamiento de ticket (genera orden de trabajo)'), ('adelantar_ticket', 'Adelantó un turno en la fila de espera'), ('reordenar_ticket', 'Reordenó un turno en la fila de espera'), ('avanzar_turno', 'Avanzó la pantalla de turnos (siguiente)'), ('enviar_reporte_diario', 'Envío de reporte diario'), ('registrar_pago_planilla', 'Registro de pago de planilla')], max_length=30),
        ),
    ]
