# Generated by Django 5.2.16 on 2026-09-02 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_pagoplanilla_numero_boleta_and_more'),
        ('pacientes', '0033_alter_ticket_options_ticket_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comprobante', models.FileField(upload_to='comprobantes_planilla/%Y/%m/', verbose_name='comprobante (boleta o transferencia)')),
                ('numero_boleta', models.CharField(blank=True, max_length=60, verbose_name='número de boleta / referencia')),
                ('verificado', models.BooleanField(default=False, help_text='El OCR del comprobante confirmó el monto (y el número de boleta, si se indicó).')),
                ('verificacion_nota', models.CharField(blank=True, max_length=255)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField(help_text='Último día del período, incluido.')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_comision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago de comisiones',
                'verbose_name_plural': 'pagos de comisiones',
                'db_table': 'pagos_comision',
                'ordering': ['-hasta', '-desde'],
            },
        ),
        migrations.CreateModel(
            name='PagoComisionLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_cita', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.cita')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='accounts.pagocomision')),
            ],
            options={
                'db_table': 'pagos_comision_lineas',
                'unique_together': {('cita', 'rol_en_cita')},
            },
        ),
        migrations.CreateModel(
            name='PagoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comprobante', models.FileField(upload_to='comprobantes_planilla/%Y/%m/', verbose_name='comprobante (boleta o transferencia)')),
                ('numero_boleta', models.CharField(blank=True, max_length=60, verbose_name='número de boleta / referencia')),
                ('verificado', models.BooleanField(default=False, help_text='El OCR del comprobante confirmó el monto (y el número de boleta, si se indicó).')),
                ('verificacion_nota', models.CharField(blank=True, max_length=255)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField()),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_salario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago de salario',
                'verbose_name_plural': 'pagos de salario',
                'db_table': 'pagos_salario',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('usuario', 'anio', 'mes')},
            },
        ),
        migrations.DeleteModel(
            name='PagoPlanilla',
        ),
    ]
