# Generated by Django 5.2.16 on 2026-09-02 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SQL_CREAR_TABLAS = """
CREATE TABLE IF NOT EXISTS `pagos_planilla` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `anio` int unsigned NOT NULL,
    `mes` smallint unsigned NOT NULL,
    `salario_base` decimal(10,2) NOT NULL,
    `comisiones` decimal(10,2) NOT NULL,
    `total` decimal(10,2) NOT NULL,
    `comprobante` varchar(100) NOT NULL,
    `notas` varchar(255) NOT NULL,
    `creado_en` datetime(6) NOT NULL,
    `actualizado_en` datetime(6) NOT NULL,
    `registrado_por_id` bigint NOT NULL,
    `usuario_id` bigint NOT NULL,
    `numero_boleta` varchar(60) NOT NULL,
    `verificacion_nota` varchar(255) NOT NULL,
    `verificado` tinyint(1) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `pagos_planilla_usuario_id_anio_mes` (`usuario_id`,`anio`,`mes`),
    KEY `pagos_planilla_registrado_por_id` (`registrado_por_id`),
    CONSTRAINT `pagos_planilla_registrado_por_fk` FOREIGN KEY (`registrado_por_id`) REFERENCES `usuarios` (`id`),
    CONSTRAINT `pagos_planilla_usuario_fk` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `lineas_comision_liquidadas` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `rol_en_cita` varchar(20) NOT NULL,
    `comision` decimal(10,2) NOT NULL,
    `creado_en` datetime(6) NOT NULL,
    `cita_id` bigint NOT NULL,
    `pago_id` bigint NOT NULL,
    `usuario_id` bigint NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_linea_comision_liquidada` (`usuario_id`,`cita_id`,`rol_en_cita`),
    KEY `lineas_comision_liquidadas_cita_id` (`cita_id`),
    KEY `lineas_comision_liquidadas_pago_id` (`pago_id`),
    CONSTRAINT `lineas_comision_liquidadas_cita_fk` FOREIGN KEY (`cita_id`) REFERENCES `citas` (`id`),
    CONSTRAINT `lineas_comision_liquidadas_pago_fk` FOREIGN KEY (`pago_id`) REFERENCES `pagos_planilla` (`id`),
    CONSTRAINT `lineas_comision_liquidadas_usuario_fk` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_bitacora_accion'),
        ('pacientes', '0033_alter_ticket_options_ticket_orden'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(SQL_CREAR_TABLAS),
            ],
            state_operations=[
                migrations.CreateModel(
            name='LineaComisionLiquidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_cita', models.CharField(choices=[('tecnico', 'Técnico'), ('radiologo', 'Radiólogo')], max_length=20)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_comision_liquidadas', to='pacientes.cita')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='accounts.pagoplanilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_comision_liquidadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'línea de comisión liquidada',
                'verbose_name_plural': 'líneas de comisión liquidadas',
                'db_table': 'lineas_comision_liquidadas',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'cita', 'rol_en_cita'), name='uniq_linea_comision_liquidada')],
            },
                ),
            ],
        ),
    ]
