# Generated by Django 5.2.16 on 2026-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_usuario_puede_operar_caja_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sala',
            field=models.CharField(
                blank=True, max_length=40, verbose_name='sala / consultorio',
                help_text='Solo para radiólogos: la sala donde atiende (ej. "Sala 1").',
            ),
        ),
    ]
