# Generated by Django 5.2.16 on 2026-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_usuario_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sesion_activa',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
