# Generated by Django 5.2.16 on 2026-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('recepcionista', 'Recepcionista'), ('caja', 'Caja'), ('tecnico_imagenes', 'Técnico de imágenes'), ('medico_radiologo', 'Médico radiólogo'), ('medico_remitente', 'Médico remitente')], default='administrador', max_length=25, verbose_name='rol'),
        ),
    ]
