# Generated by Django 5.2.16 on 2026-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puede_operar_caja',
            field=models.BooleanField(default=False, help_text='Permite consultar y registrar pagos de estudios.', verbose_name='puede operar Caja'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('recepcionista', 'Recepcionista'), ('tecnico_imagenes', 'Técnico de imágenes'), ('medico_radiologo', 'Médico radiólogo'), ('medico_remitente', 'Médico remitente')], default='administrador', max_length=25, verbose_name='rol'),
        ),
    ]
