# Generated by Django 5.2.16 on 2026-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_usuario_puede_operar_caja_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoplanilla',
            name='es_adelanto',
            field=models.BooleanField(default=False, help_text='Si se marca, permite procesar el pago aunque el mes no haya terminado o iniciado.', verbose_name='adelanto de sueldo'),
        ),
    ]
