# Generated by Django 5.2.16 on 2026-09-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_usuario_sala'),
        ('accounts', '0025_pagoplanilla_es_adelanto'),
    ]

    operations = [
    ]
