# Generated by Django 5.2.16 on 2026-09-15 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_bitacora_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('administrador_financiero', 'Administrador financiero'), ('recepcionista', 'Recepcionista'), ('tecnico_imagenes', 'Técnico de imágenes'), ('medico_radiologo', 'Médico radiólogo'), ('medico_remitente', 'Médico remitente')], max_length=25)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_adicionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rol adicional',
                'verbose_name_plural': 'roles adicionales',
                'db_table': 'usuarios_roles_adicionales',
                'ordering': ['usuario', 'rol'],
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
