# Generated by Django 5.2.16 on 2026-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_roladicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('login_exitoso', 'Inicio de sesión'), ('login_fallido', 'Intento de inicio de sesión fallido'), ('crear_usuario', 'Creación de usuario'), ('confirmar_correo_usuario', 'Confirmación de correo de un usuario nuevo'), ('editar_usuario', 'Edición de usuario'), ('cambiar_estado_usuario', 'Cambio de estado de usuario (suspensión/reactivación)'), ('editar_comision', 'Cambio de comisión de un usuario'), ('crear_estudio', 'Creación de estudio'), ('editar_estudio', 'Edición de estudio'), ('editar_precio_estudio', 'Cambio de precio de un estudio'), ('solicitar_cita', 'Solicitud de cita'), ('confirmar_cita', 'Confirmación de cita'), ('rechazar_cita', 'Rechazo de solicitud de cita'), ('reagendar_cita', 'Reagenda de cita'), ('marcar_llegada', 'Llegada de paciente'), ('marcar_ausente', 'Ausencia de paciente'), ('generar_orden', 'Generación de orden de trabajo'), ('adjuntar_imagenes', 'Carga de imágenes de estudio'), ('seleccionar_imagenes', 'Selección de imágenes del estudio'), ('adjuntar_informe', 'Carga de informe'), ('enviar_estudio', 'Envío de estudio al paciente'), ('registrar_ticket', 'Registro de ticket / turno'), ('procesar_ticket', 'Procesamiento de ticket (genera orden de trabajo)'), ('adelantar_ticket', 'Adelantó un turno en la fila de espera'), ('avanzar_turno', 'Avanzó la pantalla de turnos (siguiente)'), ('enviar_reporte_diario', 'Envío de reporte diario'), ('registrar_pago_planilla', 'Registro de pago de planilla'), ('crear_combo', 'Creación de combo de estudios'), ('editar_combo', 'Edición de combo de estudios'), ('marcar_cobrado', 'Marcar estudio como cobrado'), ('agregar_estudio_extra', 'Agregó un estudio extra a una cita'), ('validar_estudio', 'El técnico confirmó que el estudio es correcto'), ('solicitar_modificacion', 'El técnico pidió modificar el estudio'), ('corregir_estudio', 'Recepción modificó el estudio de una cita'), ('eliminar_cita', 'Eliminación de una cita del calendario'), ('eliminar_turno', 'Eliminación de un turno de la fila de espera')], max_length=30),
        ),
    ]
