# Generated by Django 5.2.16 on 2026-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/%Y/%m/', verbose_name='foto de perfil'),
        ),
    ]
