# Generated by Django 5.2.16 on 2026-09-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_cambio_precio_programado'),
        ('accounts', '0029_usuario_foto_perfil'),
    ]

    operations = [
    ]
