# Generated by Django 5.2.16 on 2026-10-08 06:39

from django.db import migrations, models


def marcar_usuarios_con_mfa_activo(apps, schema_editor):
    """Quien ya tenía la verificación en dos pasos activa (app vinculada)
    queda con el MFA requerido, para que siga activo ahora que solo un
    administrador puede desactivarlo."""
    Usuario = apps.get_model('accounts', 'Usuario')
    TOTPDevice = apps.get_model('otp_totp', 'TOTPDevice')
    ids = TOTPDevice.objects.filter(confirmed=True).values_list('user_id', flat=True)
    Usuario.objects.filter(pk__in=list(ids)).update(mfa_requerido=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_google_drive_respaldos'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mfa_requerido',
            field=models.BooleanField(default=False, help_text='Pide un código de la app de autenticación en cada inicio de sesión. Solo un administrador puede activarla o desactivarla.', verbose_name='verificación en dos pasos (MFA)'),
        ),
        migrations.RunPython(marcar_usuarios_con_mfa_activo, migrations.RunPython.noop),
    ]
