# Generated by Django 5.2.16 on 2026-10-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_mfa_requerido_usuario'),
        ('accounts', '0035_restaurar_respaldo_bitacora'),
    ]

    operations = [
    ]
