"""
Django settings for clinica project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from email.utils import formataddr

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-ok0%f_-*e4)pep)5mk=ku)=*ajj0_+2wpe_biw4ax^y_yi1@-c',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Prueba de "servidor central en LAN": las otras 9 máquinas de la clínica
# entran por navegador a la IP de esta PC en la red local. La IP/hostname
# se define en el .env (ALLOWED_HOSTS), separada por comas, para no tener
# que tocar código cuando cambie de red.
ALLOWED_HOSTS = [
    h.strip() for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'accounts',
    'pacientes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.SesionUnicaMiddleware',
    'pacientes.middleware.AutoMarcarAusenteMiddleware',
]

# Autenticación en dos pasos (django-otp TOTP). El emisor es lo que muestra
# la app de autenticación (Google Authenticator, Authy, etc.).
OTP_TOTP_ISSUER = 'Clínica de Imágenes'

ROOT_URLCONF = 'clinica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='clinica_imagenes'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-gt'

# La clínica está en Guatemala (UTC-6, sin horario de verano). Antes estaba
# en 'America/Lima' (UTC-5), por eso después de las 23:00 el sistema ya
# mostraba el día siguiente.
TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic junta todo acá; WhiteNoise lo sirve directo sin necesitar
# Nginx — necesario porque con DEBUG=False Django deja de servir estáticos
# solo (imprescindible para exponerlo a internet).
STATIC_ROOT = BASE_DIR / 'staticfiles'
# El storage con manifest (hashea nombres, ej. theme.b70aef88.css) exige que
# ya se haya corrido collectstatic -- si no, hasta el {% static %} de los
# templates revienta con "Missing staticfiles manifest entry". En desarrollo
# (DEBUG=True) nadie corre collectstatic antes de cada cambio de CSS, así
# que ahí se usa el storage simple de siempre; el de WhiteNoise con manifest
# solo entra cuando esto se expone (DEBUG=False).
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# --- Exposición a internet vía túnel (Cloudflare Tunnel) ---
# El túnel llega a Django como HTTP local (localhost:8005), pero en el
# navegador es HTTPS — sin esto Django cree que la conexión no es segura
# y redirige/rompe cookies en loop. Cloudflare manda X-Forwarded-Proto.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Dominio(s) públicos que van a apuntar acá (además del ALLOWED_HOSTS de LAN).
# Ej: CSRF_TRUSTED_ORIGINS=https://clinica.tudominio.com
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in config('CSRF_TRUSTED_ORIGINS', default='').split(',') if o.strip()
]

# Cookies solo por HTTPS una vez que esto ya no es puro localhost/LAN.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Por defecto Django deja la cookie de sesion viva 2 semanas aunque se
# cierre el navegador -- por eso alguien podia cerrar Chrome, abrirlo de
# nuevo y seguir adentro con el usuario anterior sin volver a loguearse.
# Con esto la sesion muere en cuanto se cierra el navegador de verdad
# (algunos navegadores con "restaurar sesion" activado pueden no borrarla,
# eso ya es comportamiento del navegador, no de Django).
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

AUTH_USER_MODEL = 'accounts.Usuario'

# Configuración para envío de correos (resultados de estudios al paciente).
# Portado del commit 758cb02 de TechBlood/ProyectoSeminarioClinica.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Si EMAIL_HOST_USER todavía no está configurado en el .env, dejamos el
# remitente por defecto de Django en vez de formatear una dirección vacía
# ("Clínica de Imágenes" <>) — esa dirección inválida hace que Django
# truene con un TypeError al armar el correo, antes de siquiera intentar
# conectarse al servidor SMTP.
DEFAULT_FROM_EMAIL = (
    formataddr(('Clínica de Imágenes', EMAIL_HOST_USER)) if EMAIL_HOST_USER else 'webmaster@localhost'
)

# Base absoluta para armar el link del visor web del estudio que se manda
# en el correo al paciente (el request no siempre está disponible al enviar).
# Por ahora local; en producción se pone el dominio real en el .env.
VISOR_BASE_URL = config('VISOR_BASE_URL', default='http://localhost:8001').rstrip('/')

# El técnico sube la carpeta completa de un estudio DICOM (adjuntar_imagenes),
# que puede traer varios cientos de archivos (una serie de TAC/resonancia).
# El límite por defecto de Django (100) es insuficiente para eso.
DATA_UPLOAD_MAX_NUMBER_FILES = 5000
